// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTnADRaEvXqQGt-DjzPtAxedHQx5vq_9c',
    appId: '1:596249424788:android:514e8ce536bebcf6d25581',
    messagingSenderId: '596249424788',
    projectId: 'expence-tracker-ef737',
    storageBucket: 'expence-tracker-ef737.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcNfoXg3li5f59N7fUOf5E9VgVWqCnBl4',
    appId: '1:596249424788:ios:2478d2a8ea7be5f5d25581',
    messagingSenderId: '596249424788',
    projectId: 'expence-tracker-ef737',
    storageBucket: 'expence-tracker-ef737.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
